FROM sahirabbask/nginx-alphine

COPY /dist/. /usr/share/nginx/html

COPY  default.conf /etc/nginx/conf.d/default.conf

#RUN apk update && apk add --no-cache apache2-utils
#RUN htpasswd -c -b /etc/nginx/.htpasswd uib uib

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
